#include <vector>

#define titulo_01 "        __                _____              __               _       __                "
#define titulo_02 "   ____/ /__  _________ _/ __(_)___     ____/ /___     _   __(_)___  / /_  ____         "
#define titulo_03 "  / __  / _ \\/ ___/ __ `/ /_/ / __ \\   / __  / __ \\   | | / / / __ \\/ __ \\/ __ \\  "
#define titulo_04 " / /_/ /  __(__  ) /_/ / __/ / /_/ /  / /_/ / /_/ /   | |/ / / / / / / / / /_/ /        "
#define titulo_05 " \\__,_/\\___/____/\\__,_/_/ /_/\\____/   \\__,_/\\____/    |___/_/_/ /_/_/ /_/\\____/  "

#define titulo_06 "         ___________   "
#define titulo_07 "        '._==_==_=_.'  "
#define titulo_08 "        .-\\:      /-.  "
#define titulo_09 "       | (|:.     |) | "
#define titulo_10 "        '-|:.     |-'  "
#define titulo_11 "          \\::.    /    "
#define titulo_12 "           '::. .'     "
#define titulo_13 "             ) (       "
#define titulo_14 "           _.' '._     "
#define titulo_15 "    Sua lógica é inegável."
#define titulo_16 " Parabéns pela sua conquista!"

#define sistema_01 "[Pressione [ENTER] para continuar.]"
#define sistema_02 "[Erro! Cobaia não encontrada.]"
#define sistema_03 "[Erro! Insira apenas valores entre 1 a 8.]"
#define sistema_04 "[Separe a resposta com [ESPAÇO] e pressione [ENTER] para confirmar.]"
#define sistema_05 "[Valor inválido! Escolha um número entre 1 e 8.]"
#define sistema_06 "Jogar novamente?[s/n]"
#define sistema_07 "***** Obrigado por jogar! *****"
#define sistema_08 "*******************************"
#define sistema_09 "[ERRO]: Sistema operacional incompatível."

#define inst_01 "	Desafio do vinho envenenado."
#define inst_02 "- 8 garrafas de vinho foram separadas em uma mesa."
#define inst_03 "- 1 das garrafas foi envenenada."
#define inst_04 "- 3 cobaias tomarão as garrafas de vinho."
#define inst_05 "- Você deve escolher quais garrafas cada cobaia beberá."
#define inst_06 "   Após sua escolha, as cobaias serão reveladas."
#define inst_07 "- Caso ela esteja morta, será representada com um X."
#define inst_08 "- Caso ela esteja viva, será representada com um O."
#define inst_09 "- Seu objetivo é descobrir qual é a garrafa envenenada através do raciocínio lógico."
#define inst_10 "   Vamos ao desafio?"

#define garrafa_01 " __   __   __   __   __   __   __   __ "
#define garrafa_02 " ||   ||   ||   ||   ||   ||   ||   || "
#define garrafa_03 "/  \\ /  \\ /  \\ /  \\ /  \\ /  \\ /  \\ /  \\"
#define garrafa_04 "|1ª| |2ª| |3ª| |4ª| |5ª| |6ª| |7ª| |8ª|"
#define garrafa_05 "|  | |  | |  | |  | |  | |  | |  | |  |"
#define garrafa_06 "|__| |__| |__| |__| |__| |__| |__| |__|"

#define jogo_01 "Qual(is) garrafa(s) a "
#define jogo_02 "ª cobaia deve beber?"

#define resposta_01 "Veja abaixo como ficaram as cobaias:"
#define resposta_02 "[X = Morta | O = Viva]"
#define resposta_03 "  Cobaias: "
#define resposta_04 "1ª 2ª 3ª"
#define resposta_05 "Digite o número da garrafa que você acredita estar envenenada: "

#define resultado_01 "Parabéns! A "
#define resultado_02 "ª garrafa realmente estava envenenada!"
#define resultado_03 "--------------------------------------------------"
#define resultado_04 "| Você é muito diligente! Sua lógica é inegável. |"
#define resultado_05 "| Nenhum desafio é o suficiente para você.       |"
#define resultado_06 "| Jogue novamente para receber seu prêmio!       |"
#define resultado_07 "------------------------------------------------------------------"
#define resultado_08 "| Sua lógica é infalível. Ou será que foi apenas sorte?          |"
#define resultado_09 "| Continue jogando para demonstrar sua capacidade de raciocínio. |"
#define resultado_10 "| [Pontos: "
#define resultado_11 "/3]                                                  |"
#define resultado_12 "Infelizmente a sua resposta está errada..."
#define resultado_13 "-------------------------------------------------------------"
#define resultado_14 "| Mas não se preocupe!                                      |"
#define resultado_15 "| Aqui está seu prêmio de consolação: Uma garrafa de vinho! |"
#define resultado_16 "| Muah, Muah, Muah...                                       |"
#define resultado_17 "/3]                                             |"

#define creditos_01 "-------------------------------"
#define creditos_02 "|         Criado por          |"
#define creditos_03 "|        Gabriel Paez         |"
#define creditos_04 "| gabrielpcoliveira@gmail.com |"
